// Code generated by hertz generator.

package crawl

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	crawl "media_agent/hertz_gen/model/xhs_service/crawl"
	serverjwt "media_agent/hertz_infra/serverhertz/jwt"
	domain "media_agent/xhs_service/biz/domain/crawl"
	service "media_agent/xhs_service/biz/service/crawl"
)

// StartCrawlTask .
// @router /v1/organizations/:organization_id/crawl/tasks [POST]
func StartCrawlTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req crawl.StartCrawlTaskRequest
	err = c.BindPath(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	var taskInput crawl.CrawlTaskInput
	err = c.BindJSON(&taskInput)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	req.Task = &taskInput
	if crawlService == nil {
		c.String(consts.StatusInternalServerError, "crawl service is not configured")
		return
	}
	principal, ok := serverjwt.PrincipalFromContext(ctx)
	if !ok {
		writeServiceError(c, service.ErrUnauthenticated)
		return
	}
	task, err := crawlService.StartTask(ctx, service.StartTaskCommand{
		Subject: principal.Subject, OrganizationID: req.GetOrganizationId(), Keywords: req.GetTask().GetKeywords(),
	})
	if err != nil {
		writeServiceError(c, err)
		return
	}
	resp := &crawl.StartCrawlTaskResponse{TaskId: task.ID, Status: task.Status}
	c.JSON(consts.StatusOK, resp)
	return
}

// ListCrawlContents .
// @router /v1/organizations/:organization_id/crawl/contents [GET]
func ListCrawlContents(ctx context.Context, c *app.RequestContext) {
	var err error
	var req crawl.ListCrawlContentsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	principal, ok := serverjwt.PrincipalFromContext(ctx)
	if !ok {
		writeServiceError(c, service.ErrUnauthenticated)
		return
	}
	contents, err := crawlService.ListContents(ctx, service.OrganizationQuery{Subject: principal.Subject, OrganizationID: req.GetOrganizationId()})
	if err != nil {
		writeServiceError(c, err)
		return
	}
	resp := &crawl.ListCrawlContentsResponse{}
	for _, content := range contents {
		resp.Contents = append(resp.Contents, &crawl.CrawlContent{Id: content.ID, Title: content.Title, SourceKeyword: content.SourceKeyword})
	}
	c.JSON(consts.StatusOK, resp)
}

// GetKeywords .
// @router /v1/organizations/:organization_id/crawl/keywords [GET]
func GetKeywords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req crawl.GetKeywordsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	principal, ok := serverjwt.PrincipalFromContext(ctx)
	if !ok {
		writeServiceError(c, service.ErrUnauthenticated)
		return
	}
	keywords, err := crawlService.GetKeywords(ctx, service.OrganizationQuery{Subject: principal.Subject, OrganizationID: req.GetOrganizationId()})
	if err != nil {
		writeServiceError(c, err)
		return
	}
	c.JSON(consts.StatusOK, &crawl.GetKeywordsResponse{Keywords: keywords})
}

// UpdateKeywords .
// @router /v1/organizations/:organization_id/crawl/keywords [PUT]
func UpdateKeywords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req crawl.UpdateKeywordsRequest
	err = c.BindPath(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	var keywordInput crawl.KeywordInput
	err = c.BindJSON(&keywordInput)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	req.Keywords = &keywordInput

	principal, ok := serverjwt.PrincipalFromContext(ctx)
	if !ok {
		writeServiceError(c, service.ErrUnauthenticated)
		return
	}
	keywords, err := crawlService.UpdateKeywords(ctx, service.UpdateKeywordsCommand{Subject: principal.Subject, OrganizationID: req.GetOrganizationId(), Keywords: req.GetKeywords().GetValues()})
	if err != nil {
		writeServiceError(c, err)
		return
	}
	c.JSON(consts.StatusOK, &crawl.UpdateKeywordsResponse{Keywords: keywords})
}

func writeServiceError(c *app.RequestContext, err error) {
	status := consts.StatusInternalServerError
	switch {
	case errors.Is(err, service.ErrUnauthenticated):
		status = consts.StatusUnauthorized
	case errors.Is(err, service.ErrForbidden):
		status = consts.StatusForbidden
	case errors.Is(err, service.ErrDependencyUnavailable):
		status = consts.StatusServiceUnavailable
	case errors.Is(err, domain.ErrInvalidInput):
		status = consts.StatusBadRequest
	}
	c.AbortWithStatusJSON(status, map[string]any{"error": err.Error()})
}
