// Code generated by Kitex v0.11.3. DO NOT EDIT.
package health

import (
	server "github.com/cloudwego/kitex/server"
	v1 "media_agent/xhs_grpc/kitex_gen/grpc/health/v1"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler v1.Health, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler v1.Health, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
