// Code generated by Kitex v0.11.3. DO NOT EDIT.

package crawlservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	crawl "media_agent/xhs_grpc/kitex_gen/xhs_service/crawl"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	StartCrawlTask(ctx context.Context, Req *crawl.StartCrawlTaskRequest, callOptions ...callopt.Option) (r *crawl.StartCrawlTaskResponse, err error)
	ListCrawlContents(ctx context.Context, Req *crawl.ListCrawlContentsRequest, callOptions ...callopt.Option) (r *crawl.ListCrawlContentsResponse, err error)
	GetKeywords(ctx context.Context, Req *crawl.GetKeywordsRequest, callOptions ...callopt.Option) (r *crawl.GetKeywordsResponse, err error)
	UpdateKeywords(ctx context.Context, Req *crawl.UpdateKeywordsRequest, callOptions ...callopt.Option) (r *crawl.UpdateKeywordsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCrawlServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCrawlServiceClient struct {
	*kClient
}

func (p *kCrawlServiceClient) StartCrawlTask(ctx context.Context, Req *crawl.StartCrawlTaskRequest, callOptions ...callopt.Option) (r *crawl.StartCrawlTaskResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartCrawlTask(ctx, Req)
}

func (p *kCrawlServiceClient) ListCrawlContents(ctx context.Context, Req *crawl.ListCrawlContentsRequest, callOptions ...callopt.Option) (r *crawl.ListCrawlContentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListCrawlContents(ctx, Req)
}

func (p *kCrawlServiceClient) GetKeywords(ctx context.Context, Req *crawl.GetKeywordsRequest, callOptions ...callopt.Option) (r *crawl.GetKeywordsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetKeywords(ctx, Req)
}

func (p *kCrawlServiceClient) UpdateKeywords(ctx context.Context, Req *crawl.UpdateKeywordsRequest, callOptions ...callopt.Option) (r *crawl.UpdateKeywordsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateKeywords(ctx, Req)
}
