// Code generated by Kitex v0.11.3. DO NOT EDIT.

package crawlservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	crawl "media_agent/xhs_grpc/kitex_gen/xhs_service/crawl"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"StartCrawlTask": kitex.NewMethodInfo(
		startCrawlTaskHandler,
		newStartCrawlTaskArgs,
		newStartCrawlTaskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ListCrawlContents": kitex.NewMethodInfo(
		listCrawlContentsHandler,
		newListCrawlContentsArgs,
		newListCrawlContentsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetKeywords": kitex.NewMethodInfo(
		getKeywordsHandler,
		newGetKeywordsArgs,
		newGetKeywordsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateKeywords": kitex.NewMethodInfo(
		updateKeywordsHandler,
		newUpdateKeywordsArgs,
		newUpdateKeywordsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	crawlServiceServiceInfo                = NewServiceInfo()
	crawlServiceServiceInfoForClient       = NewServiceInfoForClient()
	crawlServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return crawlServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return crawlServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return crawlServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CrawlService"
	handlerType := (*crawl.CrawlService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "xhs_service.crawl",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func startCrawlTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(crawl.StartCrawlTaskRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(crawl.CrawlService).StartCrawlTask(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *StartCrawlTaskArgs:
		success, err := handler.(crawl.CrawlService).StartCrawlTask(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*StartCrawlTaskResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newStartCrawlTaskArgs() interface{} {
	return &StartCrawlTaskArgs{}
}

func newStartCrawlTaskResult() interface{} {
	return &StartCrawlTaskResult{}
}

type StartCrawlTaskArgs struct {
	Req *crawl.StartCrawlTaskRequest
}

func (p *StartCrawlTaskArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(crawl.StartCrawlTaskRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *StartCrawlTaskArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *StartCrawlTaskArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *StartCrawlTaskArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *StartCrawlTaskArgs) Unmarshal(in []byte) error {
	msg := new(crawl.StartCrawlTaskRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var StartCrawlTaskArgs_Req_DEFAULT *crawl.StartCrawlTaskRequest

func (p *StartCrawlTaskArgs) GetReq() *crawl.StartCrawlTaskRequest {
	if !p.IsSetReq() {
		return StartCrawlTaskArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *StartCrawlTaskArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *StartCrawlTaskArgs) GetFirstArgument() interface{} {
	return p.Req
}

type StartCrawlTaskResult struct {
	Success *crawl.StartCrawlTaskResponse
}

var StartCrawlTaskResult_Success_DEFAULT *crawl.StartCrawlTaskResponse

func (p *StartCrawlTaskResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(crawl.StartCrawlTaskResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *StartCrawlTaskResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *StartCrawlTaskResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *StartCrawlTaskResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *StartCrawlTaskResult) Unmarshal(in []byte) error {
	msg := new(crawl.StartCrawlTaskResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *StartCrawlTaskResult) GetSuccess() *crawl.StartCrawlTaskResponse {
	if !p.IsSetSuccess() {
		return StartCrawlTaskResult_Success_DEFAULT
	}
	return p.Success
}

func (p *StartCrawlTaskResult) SetSuccess(x interface{}) {
	p.Success = x.(*crawl.StartCrawlTaskResponse)
}

func (p *StartCrawlTaskResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StartCrawlTaskResult) GetResult() interface{} {
	return p.Success
}

func listCrawlContentsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(crawl.ListCrawlContentsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(crawl.CrawlService).ListCrawlContents(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListCrawlContentsArgs:
		success, err := handler.(crawl.CrawlService).ListCrawlContents(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListCrawlContentsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListCrawlContentsArgs() interface{} {
	return &ListCrawlContentsArgs{}
}

func newListCrawlContentsResult() interface{} {
	return &ListCrawlContentsResult{}
}

type ListCrawlContentsArgs struct {
	Req *crawl.ListCrawlContentsRequest
}

func (p *ListCrawlContentsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(crawl.ListCrawlContentsRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListCrawlContentsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListCrawlContentsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListCrawlContentsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListCrawlContentsArgs) Unmarshal(in []byte) error {
	msg := new(crawl.ListCrawlContentsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListCrawlContentsArgs_Req_DEFAULT *crawl.ListCrawlContentsRequest

func (p *ListCrawlContentsArgs) GetReq() *crawl.ListCrawlContentsRequest {
	if !p.IsSetReq() {
		return ListCrawlContentsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListCrawlContentsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListCrawlContentsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListCrawlContentsResult struct {
	Success *crawl.ListCrawlContentsResponse
}

var ListCrawlContentsResult_Success_DEFAULT *crawl.ListCrawlContentsResponse

func (p *ListCrawlContentsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(crawl.ListCrawlContentsResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListCrawlContentsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListCrawlContentsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListCrawlContentsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListCrawlContentsResult) Unmarshal(in []byte) error {
	msg := new(crawl.ListCrawlContentsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListCrawlContentsResult) GetSuccess() *crawl.ListCrawlContentsResponse {
	if !p.IsSetSuccess() {
		return ListCrawlContentsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListCrawlContentsResult) SetSuccess(x interface{}) {
	p.Success = x.(*crawl.ListCrawlContentsResponse)
}

func (p *ListCrawlContentsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListCrawlContentsResult) GetResult() interface{} {
	return p.Success
}

func getKeywordsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(crawl.GetKeywordsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(crawl.CrawlService).GetKeywords(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetKeywordsArgs:
		success, err := handler.(crawl.CrawlService).GetKeywords(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetKeywordsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetKeywordsArgs() interface{} {
	return &GetKeywordsArgs{}
}

func newGetKeywordsResult() interface{} {
	return &GetKeywordsResult{}
}

type GetKeywordsArgs struct {
	Req *crawl.GetKeywordsRequest
}

func (p *GetKeywordsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(crawl.GetKeywordsRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetKeywordsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetKeywordsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetKeywordsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetKeywordsArgs) Unmarshal(in []byte) error {
	msg := new(crawl.GetKeywordsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetKeywordsArgs_Req_DEFAULT *crawl.GetKeywordsRequest

func (p *GetKeywordsArgs) GetReq() *crawl.GetKeywordsRequest {
	if !p.IsSetReq() {
		return GetKeywordsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetKeywordsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetKeywordsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetKeywordsResult struct {
	Success *crawl.GetKeywordsResponse
}

var GetKeywordsResult_Success_DEFAULT *crawl.GetKeywordsResponse

func (p *GetKeywordsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(crawl.GetKeywordsResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetKeywordsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetKeywordsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetKeywordsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetKeywordsResult) Unmarshal(in []byte) error {
	msg := new(crawl.GetKeywordsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetKeywordsResult) GetSuccess() *crawl.GetKeywordsResponse {
	if !p.IsSetSuccess() {
		return GetKeywordsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetKeywordsResult) SetSuccess(x interface{}) {
	p.Success = x.(*crawl.GetKeywordsResponse)
}

func (p *GetKeywordsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetKeywordsResult) GetResult() interface{} {
	return p.Success
}

func updateKeywordsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(crawl.UpdateKeywordsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(crawl.CrawlService).UpdateKeywords(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateKeywordsArgs:
		success, err := handler.(crawl.CrawlService).UpdateKeywords(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateKeywordsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateKeywordsArgs() interface{} {
	return &UpdateKeywordsArgs{}
}

func newUpdateKeywordsResult() interface{} {
	return &UpdateKeywordsResult{}
}

type UpdateKeywordsArgs struct {
	Req *crawl.UpdateKeywordsRequest
}

func (p *UpdateKeywordsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(crawl.UpdateKeywordsRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateKeywordsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateKeywordsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateKeywordsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateKeywordsArgs) Unmarshal(in []byte) error {
	msg := new(crawl.UpdateKeywordsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateKeywordsArgs_Req_DEFAULT *crawl.UpdateKeywordsRequest

func (p *UpdateKeywordsArgs) GetReq() *crawl.UpdateKeywordsRequest {
	if !p.IsSetReq() {
		return UpdateKeywordsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateKeywordsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateKeywordsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateKeywordsResult struct {
	Success *crawl.UpdateKeywordsResponse
}

var UpdateKeywordsResult_Success_DEFAULT *crawl.UpdateKeywordsResponse

func (p *UpdateKeywordsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(crawl.UpdateKeywordsResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateKeywordsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateKeywordsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateKeywordsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateKeywordsResult) Unmarshal(in []byte) error {
	msg := new(crawl.UpdateKeywordsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateKeywordsResult) GetSuccess() *crawl.UpdateKeywordsResponse {
	if !p.IsSetSuccess() {
		return UpdateKeywordsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateKeywordsResult) SetSuccess(x interface{}) {
	p.Success = x.(*crawl.UpdateKeywordsResponse)
}

func (p *UpdateKeywordsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateKeywordsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) StartCrawlTask(ctx context.Context, Req *crawl.StartCrawlTaskRequest) (r *crawl.StartCrawlTaskResponse, err error) {
	var _args StartCrawlTaskArgs
	_args.Req = Req
	var _result StartCrawlTaskResult
	if err = p.c.Call(ctx, "StartCrawlTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListCrawlContents(ctx context.Context, Req *crawl.ListCrawlContentsRequest) (r *crawl.ListCrawlContentsResponse, err error) {
	var _args ListCrawlContentsArgs
	_args.Req = Req
	var _result ListCrawlContentsResult
	if err = p.c.Call(ctx, "ListCrawlContents", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetKeywords(ctx context.Context, Req *crawl.GetKeywordsRequest) (r *crawl.GetKeywordsResponse, err error) {
	var _args GetKeywordsArgs
	_args.Req = Req
	var _result GetKeywordsResult
	if err = p.c.Call(ctx, "GetKeywords", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateKeywords(ctx context.Context, Req *crawl.UpdateKeywordsRequest) (r *crawl.UpdateKeywordsResponse, err error) {
	var _args UpdateKeywordsArgs
	_args.Req = Req
	var _result UpdateKeywordsResult
	if err = p.c.Call(ctx, "UpdateKeywords", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
