// Code generated by Kitex v0.11.3. DO NOT EDIT.
package crawlservice

import (
	server "github.com/cloudwego/kitex/server"
	crawl "media_agent/xhs_grpc/kitex_gen/xhs_service/crawl"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler crawl.CrawlService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler crawl.CrawlService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
