// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.0
// source: xhs_service/crawl.proto

package crawl

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "media_agent/xhs_grpc/kitex_gen/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartCrawlTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Task           *CrawlTaskInput        `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartCrawlTaskRequest) Reset() {
	*x = StartCrawlTaskRequest{}
	mi := &file_xhs_service_crawl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCrawlTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCrawlTaskRequest) ProtoMessage() {}

func (x *StartCrawlTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_crawl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCrawlTaskRequest.ProtoReflect.Descriptor instead.
func (*StartCrawlTaskRequest) Descriptor() ([]byte, []int) {
	return file_xhs_service_crawl_proto_rawDescGZIP(), []int{0}
}

func (x *StartCrawlTaskRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *StartCrawlTaskRequest) GetTask() *CrawlTaskInput {
	if x != nil {
		return x.Task
	}
	return nil
}

type CrawlTaskInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      []string               `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlTaskInput) Reset() {
	*x = CrawlTaskInput{}
	mi := &file_xhs_service_crawl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlTaskInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlTaskInput) ProtoMessage() {}

func (x *CrawlTaskInput) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_crawl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlTaskInput.ProtoReflect.Descriptor instead.
func (*CrawlTaskInput) Descriptor() ([]byte, []int) {
	return file_xhs_service_crawl_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlTaskInput) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type StartCrawlTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCrawlTaskResponse) Reset() {
	*x = StartCrawlTaskResponse{}
	mi := &file_xhs_service_crawl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCrawlTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCrawlTaskResponse) ProtoMessage() {}

func (x *StartCrawlTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_crawl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCrawlTaskResponse.ProtoReflect.Descriptor instead.
func (*StartCrawlTaskResponse) Descriptor() ([]byte, []int) {
	return file_xhs_service_crawl_proto_rawDescGZIP(), []int{2}
}

func (x *StartCrawlTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StartCrawlTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListCrawlContentsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Keyword        string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListCrawlContentsRequest) Reset() {
	*x = ListCrawlContentsRequest{}
	mi := &file_xhs_service_crawl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCrawlContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCrawlContentsRequest) ProtoMessage() {}

func (x *ListCrawlContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_crawl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCrawlContentsRequest.ProtoReflect.Descriptor instead.
func (*ListCrawlContentsRequest) Descriptor() ([]byte, []int) {
	return file_xhs_service_crawl_proto_rawDescGZIP(), []int{3}
}

func (x *ListCrawlContentsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListCrawlContentsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListCrawlContentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*CrawlContent        `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCrawlContentsResponse) Reset() {
	*x = ListCrawlContentsResponse{}
	mi := &file_xhs_service_crawl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCrawlContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCrawlContentsResponse) ProtoMessage() {}

func (x *ListCrawlContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_crawl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCrawlContentsResponse.ProtoReflect.Descriptor instead.
func (*ListCrawlContentsResponse) Descriptor() ([]byte, []int) {
	return file_xhs_service_crawl_proto_rawDescGZIP(), []int{4}
}

func (x *ListCrawlContentsResponse) GetContents() []*CrawlContent {
	if x != nil {
		return x.Contents
	}
	return nil
}

type CrawlContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SourceKeyword string                 `protobuf:"bytes,3,opt,name=source_keyword,json=sourceKeyword,proto3" json:"source_keyword,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlContent) Reset() {
	*x = CrawlContent{}
	mi := &file_xhs_service_crawl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlContent) ProtoMessage() {}

func (x *CrawlContent) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_crawl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlContent.ProtoReflect.Descriptor instead.
func (*CrawlContent) Descriptor() ([]byte, []int) {
	return file_xhs_service_crawl_proto_rawDescGZIP(), []int{5}
}

func (x *CrawlContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CrawlContent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CrawlContent) GetSourceKeyword() string {
	if x != nil {
		return x.SourceKeyword
	}
	return ""
}

func (x *CrawlContent) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type GetKeywordsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetKeywordsRequest) Reset() {
	*x = GetKeywordsRequest{}
	mi := &file_xhs_service_crawl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeywordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeywordsRequest) ProtoMessage() {}

func (x *GetKeywordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_crawl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeywordsRequest.ProtoReflect.Descriptor instead.
func (*GetKeywordsRequest) Descriptor() ([]byte, []int) {
	return file_xhs_service_crawl_proto_rawDescGZIP(), []int{6}
}

func (x *GetKeywordsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetKeywordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      []string               `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeywordsResponse) Reset() {
	*x = GetKeywordsResponse{}
	mi := &file_xhs_service_crawl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeywordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeywordsResponse) ProtoMessage() {}

func (x *GetKeywordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_crawl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeywordsResponse.ProtoReflect.Descriptor instead.
func (*GetKeywordsResponse) Descriptor() ([]byte, []int) {
	return file_xhs_service_crawl_proto_rawDescGZIP(), []int{7}
}

func (x *GetKeywordsResponse) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type UpdateKeywordsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Keywords       *KeywordInput          `protobuf:"bytes,3,opt,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateKeywordsRequest) Reset() {
	*x = UpdateKeywordsRequest{}
	mi := &file_xhs_service_crawl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeywordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeywordsRequest) ProtoMessage() {}

func (x *UpdateKeywordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_crawl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeywordsRequest.ProtoReflect.Descriptor instead.
func (*UpdateKeywordsRequest) Descriptor() ([]byte, []int) {
	return file_xhs_service_crawl_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateKeywordsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateKeywordsRequest) GetKeywords() *KeywordInput {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type KeywordInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeywordInput) Reset() {
	*x = KeywordInput{}
	mi := &file_xhs_service_crawl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordInput) ProtoMessage() {}

func (x *KeywordInput) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_crawl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordInput.ProtoReflect.Descriptor instead.
func (*KeywordInput) Descriptor() ([]byte, []int) {
	return file_xhs_service_crawl_proto_rawDescGZIP(), []int{9}
}

func (x *KeywordInput) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type UpdateKeywordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      []string               `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKeywordsResponse) Reset() {
	*x = UpdateKeywordsResponse{}
	mi := &file_xhs_service_crawl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeywordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeywordsResponse) ProtoMessage() {}

func (x *UpdateKeywordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_crawl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeywordsResponse.ProtoReflect.Descriptor instead.
func (*UpdateKeywordsResponse) Descriptor() ([]byte, []int) {
	return file_xhs_service_crawl_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateKeywordsResponse) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

var File_xhs_service_crawl_proto protoreflect.FileDescriptor

const file_xhs_service_crawl_proto_rawDesc = "" +
	"\n" +
	"\x17xhs_service/crawl.proto\x12\x11xhs_service.crawl\x1a\tapi.proto\x1a\x1cgoogle/api/annotations.proto\"\x9c\x01\n" +
	"\x15StartCrawlTaskRequest\x12<\n" +
	"\x0forganization_id\x18\x02 \x01(\tB\x13һ\x18\x0forganization_idR\x0eorganizationId\x12?\n" +
	"\x04task\x18\x03 \x01(\v2!.xhs_service.crawl.CrawlTaskInputB\bʻ\x18\x04taskR\x04taskJ\x04\b\x01\x10\x02\",\n" +
	"\x0eCrawlTaskInput\x12\x1a\n" +
	"\bkeywords\x18\x01 \x03(\tR\bkeywords\"I\n" +
	"\x16StartCrawlTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x85\x01\n" +
	"\x18ListCrawlContentsRequest\x12<\n" +
	"\x0forganization_id\x18\x02 \x01(\tB\x13һ\x18\x0forganization_idR\x0eorganizationId\x12%\n" +
	"\akeyword\x18\x03 \x01(\tB\v\xb2\xbb\x18\akeywordR\akeywordJ\x04\b\x01\x10\x02\"X\n" +
	"\x19ListCrawlContentsResponse\x12;\n" +
	"\bcontents\x18\x01 \x03(\v2\x1f.xhs_service.crawl.CrawlContentR\bcontents\"w\n" +
	"\fCrawlContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0esource_keyword\x18\x03 \x01(\tR\rsourceKeyword\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"X\n" +
	"\x12GetKeywordsRequest\x12<\n" +
	"\x0forganization_id\x18\x02 \x01(\tB\x13һ\x18\x0forganization_idR\x0eorganizationIdJ\x04\b\x01\x10\x02\"1\n" +
	"\x13GetKeywordsResponse\x12\x1a\n" +
	"\bkeywords\x18\x01 \x03(\tR\bkeywords\"\xa6\x01\n" +
	"\x15UpdateKeywordsRequest\x12<\n" +
	"\x0forganization_id\x18\x02 \x01(\tB\x13һ\x18\x0forganization_idR\x0eorganizationId\x12I\n" +
	"\bkeywords\x18\x03 \x01(\v2\x1f.xhs_service.crawl.KeywordInputB\fʻ\x18\bkeywordsR\bkeywordsJ\x04\b\x01\x10\x02\"&\n" +
	"\fKeywordInput\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"4\n" +
	"\x16UpdateKeywordsResponse\x12\x1a\n" +
	"\bkeywords\x18\x01 \x03(\tR\bkeywords2\x9d\a\n" +
	"\fCrawlService\x12\xde\x01\n" +
	"\x0eStartCrawlTask\x12(.xhs_service.crawl.StartCrawlTaskRequest\x1a).xhs_service.crawl.StartCrawlTaskResponse\"w\xd2\xc1\x182/v1/xhs/organizations/:organization_id/crawl/tasks\x82\xd3\xe4\x93\x02;:\x04task\"3/v1/xhs/organizations/{organization_id}/crawl/tasks\x12\xe7\x01\n" +
	"\x11ListCrawlContents\x12+.xhs_service.crawl.ListCrawlContentsRequest\x1a,.xhs_service.crawl.ListCrawlContentsResponse\"w\xca\xc1\x185/v1/xhs/organizations/:organization_id/crawl/contents\x82\xd3\xe4\x93\x028\x126/v1/xhs/organizations/{organization_id}/crawl/contents\x12\xd5\x01\n" +
	"\vGetKeywords\x12%.xhs_service.crawl.GetKeywordsRequest\x1a&.xhs_service.crawl.GetKeywordsResponse\"w\xca\xc1\x185/v1/xhs/organizations/:organization_id/crawl/keywords\x82\xd3\xe4\x93\x028\x126/v1/xhs/organizations/{organization_id}/crawl/keywords\x12\xe9\x01\n" +
	"\x0eUpdateKeywords\x12(.xhs_service.crawl.UpdateKeywordsRequest\x1a).xhs_service.crawl.UpdateKeywordsResponse\"\x81\x01\xda\xc1\x185/v1/xhs/organizations/:organization_id/crawl/keywords\x82\xd3\xe4\x93\x02B:\bkeywords\x1a6/v1/xhs/organizations/{organization_id}/crawl/keywordsB2Z0media_agent/xhs_grpc/kitex_gen/xhs_service/crawlb\x06proto3"

var (
	file_xhs_service_crawl_proto_rawDescOnce sync.Once
	file_xhs_service_crawl_proto_rawDescData []byte
)

func file_xhs_service_crawl_proto_rawDescGZIP() []byte {
	file_xhs_service_crawl_proto_rawDescOnce.Do(func() {
		file_xhs_service_crawl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xhs_service_crawl_proto_rawDesc), len(file_xhs_service_crawl_proto_rawDesc)))
	})
	return file_xhs_service_crawl_proto_rawDescData
}

var file_xhs_service_crawl_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_xhs_service_crawl_proto_goTypes = []any{
	(*StartCrawlTaskRequest)(nil),     // 0: xhs_service.crawl.StartCrawlTaskRequest
	(*CrawlTaskInput)(nil),            // 1: xhs_service.crawl.CrawlTaskInput
	(*StartCrawlTaskResponse)(nil),    // 2: xhs_service.crawl.StartCrawlTaskResponse
	(*ListCrawlContentsRequest)(nil),  // 3: xhs_service.crawl.ListCrawlContentsRequest
	(*ListCrawlContentsResponse)(nil), // 4: xhs_service.crawl.ListCrawlContentsResponse
	(*CrawlContent)(nil),              // 5: xhs_service.crawl.CrawlContent
	(*GetKeywordsRequest)(nil),        // 6: xhs_service.crawl.GetKeywordsRequest
	(*GetKeywordsResponse)(nil),       // 7: xhs_service.crawl.GetKeywordsResponse
	(*UpdateKeywordsRequest)(nil),     // 8: xhs_service.crawl.UpdateKeywordsRequest
	(*KeywordInput)(nil),              // 9: xhs_service.crawl.KeywordInput
	(*UpdateKeywordsResponse)(nil),    // 10: xhs_service.crawl.UpdateKeywordsResponse
}
var file_xhs_service_crawl_proto_depIdxs = []int32{
	1,  // 0: xhs_service.crawl.StartCrawlTaskRequest.task:type_name -> xhs_service.crawl.CrawlTaskInput
	5,  // 1: xhs_service.crawl.ListCrawlContentsResponse.contents:type_name -> xhs_service.crawl.CrawlContent
	9,  // 2: xhs_service.crawl.UpdateKeywordsRequest.keywords:type_name -> xhs_service.crawl.KeywordInput
	0,  // 3: xhs_service.crawl.CrawlService.StartCrawlTask:input_type -> xhs_service.crawl.StartCrawlTaskRequest
	3,  // 4: xhs_service.crawl.CrawlService.ListCrawlContents:input_type -> xhs_service.crawl.ListCrawlContentsRequest
	6,  // 5: xhs_service.crawl.CrawlService.GetKeywords:input_type -> xhs_service.crawl.GetKeywordsRequest
	8,  // 6: xhs_service.crawl.CrawlService.UpdateKeywords:input_type -> xhs_service.crawl.UpdateKeywordsRequest
	2,  // 7: xhs_service.crawl.CrawlService.StartCrawlTask:output_type -> xhs_service.crawl.StartCrawlTaskResponse
	4,  // 8: xhs_service.crawl.CrawlService.ListCrawlContents:output_type -> xhs_service.crawl.ListCrawlContentsResponse
	7,  // 9: xhs_service.crawl.CrawlService.GetKeywords:output_type -> xhs_service.crawl.GetKeywordsResponse
	10, // 10: xhs_service.crawl.CrawlService.UpdateKeywords:output_type -> xhs_service.crawl.UpdateKeywordsResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_xhs_service_crawl_proto_init() }
func file_xhs_service_crawl_proto_init() {
	if File_xhs_service_crawl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xhs_service_crawl_proto_rawDesc), len(file_xhs_service_crawl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xhs_service_crawl_proto_goTypes,
		DependencyIndexes: file_xhs_service_crawl_proto_depIdxs,
		MessageInfos:      file_xhs_service_crawl_proto_msgTypes,
	}.Build()
	File_xhs_service_crawl_proto = out.File
	file_xhs_service_crawl_proto_goTypes = nil
	file_xhs_service_crawl_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.11.3. DO NOT EDIT.

type CrawlService interface {
	StartCrawlTask(ctx context.Context, req *StartCrawlTaskRequest) (res *StartCrawlTaskResponse, err error)
	ListCrawlContents(ctx context.Context, req *ListCrawlContentsRequest) (res *ListCrawlContentsResponse, err error)
	GetKeywords(ctx context.Context, req *GetKeywordsRequest) (res *GetKeywordsResponse, err error)
	UpdateKeywords(ctx context.Context, req *UpdateKeywordsRequest) (res *UpdateKeywordsResponse, err error)
}
