// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package crawl

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
	annotations "google.golang.org/genproto/googleapis/api/annotations"
	api "media_agent/xhs_grpc/kitex_gen/api"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *StartCrawlTaskRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_StartCrawlTaskRequest[number], err)
}

func (x *StartCrawlTaskRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.OrganizationId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *StartCrawlTaskRequest) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	var v CrawlTaskInput
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Task = &v
	return offset, nil
}

func (x *CrawlTaskInput) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CrawlTaskInput[number], err)
}

func (x *CrawlTaskInput) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v string
	v, offset, err = fastpb.ReadString(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Keywords = append(x.Keywords, v)
	return offset, err
}

func (x *StartCrawlTaskResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_StartCrawlTaskResponse[number], err)
}

func (x *StartCrawlTaskResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.TaskId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *StartCrawlTaskResponse) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Status, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListCrawlContentsRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListCrawlContentsRequest[number], err)
}

func (x *ListCrawlContentsRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.OrganizationId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListCrawlContentsRequest) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.Keyword, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListCrawlContentsResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListCrawlContentsResponse[number], err)
}

func (x *ListCrawlContentsResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v CrawlContent
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Contents = append(x.Contents, &v)
	return offset, nil
}

func (x *CrawlContent) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_CrawlContent[number], err)
}

func (x *CrawlContent) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CrawlContent) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Title, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CrawlContent) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.SourceKeyword, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *CrawlContent) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Platform, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetKeywordsRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetKeywordsRequest[number], err)
}

func (x *GetKeywordsRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.OrganizationId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *GetKeywordsResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_GetKeywordsResponse[number], err)
}

func (x *GetKeywordsResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v string
	v, offset, err = fastpb.ReadString(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Keywords = append(x.Keywords, v)
	return offset, err
}

func (x *UpdateKeywordsRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_UpdateKeywordsRequest[number], err)
}

func (x *UpdateKeywordsRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.OrganizationId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *UpdateKeywordsRequest) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	var v KeywordInput
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Keywords = &v
	return offset, nil
}

func (x *KeywordInput) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_KeywordInput[number], err)
}

func (x *KeywordInput) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v string
	v, offset, err = fastpb.ReadString(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Values = append(x.Values, v)
	return offset, err
}

func (x *UpdateKeywordsResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_UpdateKeywordsResponse[number], err)
}

func (x *UpdateKeywordsResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v string
	v, offset, err = fastpb.ReadString(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Keywords = append(x.Keywords, v)
	return offset, err
}

func (x *StartCrawlTaskRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *StartCrawlTaskRequest) fastWriteField2(buf []byte) (offset int) {
	if x.OrganizationId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetOrganizationId())
	return offset
}

func (x *StartCrawlTaskRequest) fastWriteField3(buf []byte) (offset int) {
	if x.Task == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 3, x.GetTask())
	return offset
}

func (x *CrawlTaskInput) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *CrawlTaskInput) fastWriteField1(buf []byte) (offset int) {
	if len(x.Keywords) == 0 {
		return offset
	}
	for i := range x.GetKeywords() {
		offset += fastpb.WriteString(buf[offset:], 1, x.GetKeywords()[i])
	}
	return offset
}

func (x *StartCrawlTaskResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *StartCrawlTaskResponse) fastWriteField1(buf []byte) (offset int) {
	if x.TaskId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetTaskId())
	return offset
}

func (x *StartCrawlTaskResponse) fastWriteField2(buf []byte) (offset int) {
	if x.Status == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetStatus())
	return offset
}

func (x *ListCrawlContentsRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *ListCrawlContentsRequest) fastWriteField2(buf []byte) (offset int) {
	if x.OrganizationId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetOrganizationId())
	return offset
}

func (x *ListCrawlContentsRequest) fastWriteField3(buf []byte) (offset int) {
	if x.Keyword == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetKeyword())
	return offset
}

func (x *ListCrawlContentsResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *ListCrawlContentsResponse) fastWriteField1(buf []byte) (offset int) {
	if x.Contents == nil {
		return offset
	}
	for i := range x.GetContents() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetContents()[i])
	}
	return offset
}

func (x *CrawlContent) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *CrawlContent) fastWriteField1(buf []byte) (offset int) {
	if x.Id == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetId())
	return offset
}

func (x *CrawlContent) fastWriteField2(buf []byte) (offset int) {
	if x.Title == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetTitle())
	return offset
}

func (x *CrawlContent) fastWriteField3(buf []byte) (offset int) {
	if x.SourceKeyword == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetSourceKeyword())
	return offset
}

func (x *CrawlContent) fastWriteField4(buf []byte) (offset int) {
	if x.Platform == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetPlatform())
	return offset
}

func (x *GetKeywordsRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *GetKeywordsRequest) fastWriteField2(buf []byte) (offset int) {
	if x.OrganizationId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetOrganizationId())
	return offset
}

func (x *GetKeywordsResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *GetKeywordsResponse) fastWriteField1(buf []byte) (offset int) {
	if len(x.Keywords) == 0 {
		return offset
	}
	for i := range x.GetKeywords() {
		offset += fastpb.WriteString(buf[offset:], 1, x.GetKeywords()[i])
	}
	return offset
}

func (x *UpdateKeywordsRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	return offset
}

func (x *UpdateKeywordsRequest) fastWriteField2(buf []byte) (offset int) {
	if x.OrganizationId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetOrganizationId())
	return offset
}

func (x *UpdateKeywordsRequest) fastWriteField3(buf []byte) (offset int) {
	if x.Keywords == nil {
		return offset
	}
	offset += fastpb.WriteMessage(buf[offset:], 3, x.GetKeywords())
	return offset
}

func (x *KeywordInput) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *KeywordInput) fastWriteField1(buf []byte) (offset int) {
	if len(x.Values) == 0 {
		return offset
	}
	for i := range x.GetValues() {
		offset += fastpb.WriteString(buf[offset:], 1, x.GetValues()[i])
	}
	return offset
}

func (x *UpdateKeywordsResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *UpdateKeywordsResponse) fastWriteField1(buf []byte) (offset int) {
	if len(x.Keywords) == 0 {
		return offset
	}
	for i := range x.GetKeywords() {
		offset += fastpb.WriteString(buf[offset:], 1, x.GetKeywords()[i])
	}
	return offset
}

func (x *StartCrawlTaskRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *StartCrawlTaskRequest) sizeField2() (n int) {
	if x.OrganizationId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetOrganizationId())
	return n
}

func (x *StartCrawlTaskRequest) sizeField3() (n int) {
	if x.Task == nil {
		return n
	}
	n += fastpb.SizeMessage(3, x.GetTask())
	return n
}

func (x *CrawlTaskInput) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *CrawlTaskInput) sizeField1() (n int) {
	if len(x.Keywords) == 0 {
		return n
	}
	for i := range x.GetKeywords() {
		n += fastpb.SizeString(1, x.GetKeywords()[i])
	}
	return n
}

func (x *StartCrawlTaskResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *StartCrawlTaskResponse) sizeField1() (n int) {
	if x.TaskId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetTaskId())
	return n
}

func (x *StartCrawlTaskResponse) sizeField2() (n int) {
	if x.Status == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetStatus())
	return n
}

func (x *ListCrawlContentsRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *ListCrawlContentsRequest) sizeField2() (n int) {
	if x.OrganizationId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetOrganizationId())
	return n
}

func (x *ListCrawlContentsRequest) sizeField3() (n int) {
	if x.Keyword == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetKeyword())
	return n
}

func (x *ListCrawlContentsResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *ListCrawlContentsResponse) sizeField1() (n int) {
	if x.Contents == nil {
		return n
	}
	for i := range x.GetContents() {
		n += fastpb.SizeMessage(1, x.GetContents()[i])
	}
	return n
}

func (x *CrawlContent) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *CrawlContent) sizeField1() (n int) {
	if x.Id == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetId())
	return n
}

func (x *CrawlContent) sizeField2() (n int) {
	if x.Title == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetTitle())
	return n
}

func (x *CrawlContent) sizeField3() (n int) {
	if x.SourceKeyword == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetSourceKeyword())
	return n
}

func (x *CrawlContent) sizeField4() (n int) {
	if x.Platform == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetPlatform())
	return n
}

func (x *GetKeywordsRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField2()
	return n
}

func (x *GetKeywordsRequest) sizeField2() (n int) {
	if x.OrganizationId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetOrganizationId())
	return n
}

func (x *GetKeywordsResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *GetKeywordsResponse) sizeField1() (n int) {
	if len(x.Keywords) == 0 {
		return n
	}
	for i := range x.GetKeywords() {
		n += fastpb.SizeString(1, x.GetKeywords()[i])
	}
	return n
}

func (x *UpdateKeywordsRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField2()
	n += x.sizeField3()
	return n
}

func (x *UpdateKeywordsRequest) sizeField2() (n int) {
	if x.OrganizationId == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetOrganizationId())
	return n
}

func (x *UpdateKeywordsRequest) sizeField3() (n int) {
	if x.Keywords == nil {
		return n
	}
	n += fastpb.SizeMessage(3, x.GetKeywords())
	return n
}

func (x *KeywordInput) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *KeywordInput) sizeField1() (n int) {
	if len(x.Values) == 0 {
		return n
	}
	for i := range x.GetValues() {
		n += fastpb.SizeString(1, x.GetValues()[i])
	}
	return n
}

func (x *UpdateKeywordsResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *UpdateKeywordsResponse) sizeField1() (n int) {
	if len(x.Keywords) == 0 {
		return n
	}
	for i := range x.GetKeywords() {
		n += fastpb.SizeString(1, x.GetKeywords()[i])
	}
	return n
}

var fieldIDToName_StartCrawlTaskRequest = map[int32]string{
	2: "OrganizationId",
	3: "Task",
}

var fieldIDToName_CrawlTaskInput = map[int32]string{
	1: "Keywords",
}

var fieldIDToName_StartCrawlTaskResponse = map[int32]string{
	1: "TaskId",
	2: "Status",
}

var fieldIDToName_ListCrawlContentsRequest = map[int32]string{
	2: "OrganizationId",
	3: "Keyword",
}

var fieldIDToName_ListCrawlContentsResponse = map[int32]string{
	1: "Contents",
}

var fieldIDToName_CrawlContent = map[int32]string{
	1: "Id",
	2: "Title",
	3: "SourceKeyword",
	4: "Platform",
}

var fieldIDToName_GetKeywordsRequest = map[int32]string{
	2: "OrganizationId",
}

var fieldIDToName_GetKeywordsResponse = map[int32]string{
	1: "Keywords",
}

var fieldIDToName_UpdateKeywordsRequest = map[int32]string{
	2: "OrganizationId",
	3: "Keywords",
}

var fieldIDToName_KeywordInput = map[int32]string{
	1: "Values",
}

var fieldIDToName_UpdateKeywordsResponse = map[int32]string{
	1: "Keywords",
}

var _ = api.File_api_proto
var _ = annotations.File_google_api_annotations_proto
