// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.0
// source: social_service/social.proto

package social_service

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListMyOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrganizationsRequest) Reset() {
	*x = ListMyOrganizationsRequest{}
	mi := &file_social_service_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrganizationsRequest) ProtoMessage() {}

func (x *ListMyOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListMyOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_social_service_social_proto_rawDescGZIP(), []int{0}
}

type ListMyOrganizationsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Organizations []*OrganizationMembership `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrganizationsResponse) Reset() {
	*x = ListMyOrganizationsResponse{}
	mi := &file_social_service_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrganizationsResponse) ProtoMessage() {}

func (x *ListMyOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListMyOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_social_service_social_proto_rawDescGZIP(), []int{1}
}

func (x *ListMyOrganizationsResponse) GetOrganizations() []*OrganizationMembership {
	if x != nil {
		return x.Organizations
	}
	return nil
}

type OrganizationMembership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMembership) Reset() {
	*x = OrganizationMembership{}
	mi := &file_social_service_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMembership) ProtoMessage() {}

func (x *OrganizationMembership) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMembership.ProtoReflect.Descriptor instead.
func (*OrganizationMembership) Descriptor() ([]byte, []int) {
	return file_social_service_social_proto_rawDescGZIP(), []int{2}
}

func (x *OrganizationMembership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationMembership) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type SearchContentsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Keyword        string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchContentsRequest) Reset() {
	*x = SearchContentsRequest{}
	mi := &file_social_service_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContentsRequest) ProtoMessage() {}

func (x *SearchContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContentsRequest.ProtoReflect.Descriptor instead.
func (*SearchContentsRequest) Descriptor() ([]byte, []int) {
	return file_social_service_social_proto_rawDescGZIP(), []int{3}
}

func (x *SearchContentsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SearchContentsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type SearchContentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*SocialContent       `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchContentsResponse) Reset() {
	*x = SearchContentsResponse{}
	mi := &file_social_service_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchContentsResponse) ProtoMessage() {}

func (x *SearchContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchContentsResponse.ProtoReflect.Descriptor instead.
func (*SearchContentsResponse) Descriptor() ([]byte, []int) {
	return file_social_service_social_proto_rawDescGZIP(), []int{4}
}

func (x *SearchContentsResponse) GetContents() []*SocialContent {
	if x != nil {
		return x.Contents
	}
	return nil
}

type SocialContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SourceKeyword string                 `protobuf:"bytes,3,opt,name=source_keyword,json=sourceKeyword,proto3" json:"source_keyword,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialContent) Reset() {
	*x = SocialContent{}
	mi := &file_social_service_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialContent) ProtoMessage() {}

func (x *SocialContent) ProtoReflect() protoreflect.Message {
	mi := &file_social_service_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialContent.ProtoReflect.Descriptor instead.
func (*SocialContent) Descriptor() ([]byte, []int) {
	return file_social_service_social_proto_rawDescGZIP(), []int{5}
}

func (x *SocialContent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SocialContent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SocialContent) GetSourceKeyword() string {
	if x != nil {
		return x.SourceKeyword
	}
	return ""
}

func (x *SocialContent) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_social_service_social_proto protoreflect.FileDescriptor

const file_social_service_social_proto_rawDesc = "" +
	"\n" +
	"\x1bsocial_service/social.proto\x12\x0esocial_service\x1a\x1cgoogle/api/annotations.proto\"\x1c\n" +
	"\x1aListMyOrganizationsRequest\"k\n" +
	"\x1bListMyOrganizationsResponse\x12L\n" +
	"\rorganizations\x18\x01 \x03(\v2&.social_service.OrganizationMembershipR\rorganizations\">\n" +
	"\x16OrganizationMembership\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\"Z\n" +
	"\x15SearchContentsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\"S\n" +
	"\x16SearchContentsResponse\x129\n" +
	"\bcontents\x18\x01 \x03(\v2\x1d.social_service.SocialContentR\bcontents\"x\n" +
	"\rSocialContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0esource_keyword\x18\x03 \x01(\tR\rsourceKeyword\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform2\xc4\x02\n" +
	"\rSocialService\x12\x93\x01\n" +
	"\x13ListMyOrganizations\x12*.social_service.ListMyOrganizationsRequest\x1a+.social_service.ListMyOrganizationsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/social/me/organizations\x12\x9c\x01\n" +
	"\x0eSearchContents\x12%.social_service.SearchContentsRequest\x1a&.social_service.SearchContentsResponse\";\x82\xd3\xe4\x93\x025\x123/v1/social/organizations/{organization_id}/contentsB2Z0media_agent/social_grpc/kitex_gen/social_serviceb\x06proto3"

var (
	file_social_service_social_proto_rawDescOnce sync.Once
	file_social_service_social_proto_rawDescData []byte
)

func file_social_service_social_proto_rawDescGZIP() []byte {
	file_social_service_social_proto_rawDescOnce.Do(func() {
		file_social_service_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_service_social_proto_rawDesc), len(file_social_service_social_proto_rawDesc)))
	})
	return file_social_service_social_proto_rawDescData
}

var file_social_service_social_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_social_service_social_proto_goTypes = []any{
	(*ListMyOrganizationsRequest)(nil),  // 0: social_service.ListMyOrganizationsRequest
	(*ListMyOrganizationsResponse)(nil), // 1: social_service.ListMyOrganizationsResponse
	(*OrganizationMembership)(nil),      // 2: social_service.OrganizationMembership
	(*SearchContentsRequest)(nil),       // 3: social_service.SearchContentsRequest
	(*SearchContentsResponse)(nil),      // 4: social_service.SearchContentsResponse
	(*SocialContent)(nil),               // 5: social_service.SocialContent
}
var file_social_service_social_proto_depIdxs = []int32{
	2, // 0: social_service.ListMyOrganizationsResponse.organizations:type_name -> social_service.OrganizationMembership
	5, // 1: social_service.SearchContentsResponse.contents:type_name -> social_service.SocialContent
	0, // 2: social_service.SocialService.ListMyOrganizations:input_type -> social_service.ListMyOrganizationsRequest
	3, // 3: social_service.SocialService.SearchContents:input_type -> social_service.SearchContentsRequest
	1, // 4: social_service.SocialService.ListMyOrganizations:output_type -> social_service.ListMyOrganizationsResponse
	4, // 5: social_service.SocialService.SearchContents:output_type -> social_service.SearchContentsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_social_service_social_proto_init() }
func file_social_service_social_proto_init() {
	if File_social_service_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_service_social_proto_rawDesc), len(file_social_service_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_service_social_proto_goTypes,
		DependencyIndexes: file_social_service_social_proto_depIdxs,
		MessageInfos:      file_social_service_social_proto_msgTypes,
	}.Build()
	File_social_service_social_proto = out.File
	file_social_service_social_proto_goTypes = nil
	file_social_service_social_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.11.3. DO NOT EDIT.

type SocialService interface {
	ListMyOrganizations(ctx context.Context, req *ListMyOrganizationsRequest) (res *ListMyOrganizationsResponse, err error)
	SearchContents(ctx context.Context, req *SearchContentsRequest) (res *SearchContentsResponse, err error)
}
