// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package social_service

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
	annotations "google.golang.org/genproto/googleapis/api/annotations"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *ListMyOrganizationsRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
}

func (x *ListMyOrganizationsResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListMyOrganizationsResponse[number], err)
}

func (x *ListMyOrganizationsResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v OrganizationMembership
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Organizations = append(x.Organizations, &v)
	return offset, nil
}

func (x *OrganizationMembership) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_OrganizationMembership[number], err)
}

func (x *OrganizationMembership) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *OrganizationMembership) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	var v string
	v, offset, err = fastpb.ReadString(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Roles = append(x.Roles, v)
	return offset, err
}

func (x *SearchContentsRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SearchContentsRequest[number], err)
}

func (x *SearchContentsRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.OrganizationId, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SearchContentsRequest) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Keyword, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SearchContentsResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SearchContentsResponse[number], err)
}

func (x *SearchContentsResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v SocialContent
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Contents = append(x.Contents, &v)
	return offset, nil
}

func (x *SocialContent) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 3:
		offset, err = x.fastReadField3(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 4:
		offset, err = x.fastReadField4(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SocialContent[number], err)
}

func (x *SocialContent) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SocialContent) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	x.Title, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SocialContent) fastReadField3(buf []byte, _type int8) (offset int, err error) {
	x.SourceKeyword, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SocialContent) fastReadField4(buf []byte, _type int8) (offset int, err error) {
	x.Platform, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *ListMyOrganizationsRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	return offset
}

func (x *ListMyOrganizationsResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *ListMyOrganizationsResponse) fastWriteField1(buf []byte) (offset int) {
	if x.Organizations == nil {
		return offset
	}
	for i := range x.GetOrganizations() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetOrganizations()[i])
	}
	return offset
}

func (x *OrganizationMembership) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *OrganizationMembership) fastWriteField1(buf []byte) (offset int) {
	if x.Id == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetId())
	return offset
}

func (x *OrganizationMembership) fastWriteField2(buf []byte) (offset int) {
	if len(x.Roles) == 0 {
		return offset
	}
	for i := range x.GetRoles() {
		offset += fastpb.WriteString(buf[offset:], 2, x.GetRoles()[i])
	}
	return offset
}

func (x *SearchContentsRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *SearchContentsRequest) fastWriteField1(buf []byte) (offset int) {
	if x.OrganizationId == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetOrganizationId())
	return offset
}

func (x *SearchContentsRequest) fastWriteField2(buf []byte) (offset int) {
	if x.Keyword == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetKeyword())
	return offset
}

func (x *SearchContentsResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *SearchContentsResponse) fastWriteField1(buf []byte) (offset int) {
	if x.Contents == nil {
		return offset
	}
	for i := range x.GetContents() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetContents()[i])
	}
	return offset
}

func (x *SocialContent) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	offset += x.fastWriteField3(buf[offset:])
	offset += x.fastWriteField4(buf[offset:])
	return offset
}

func (x *SocialContent) fastWriteField1(buf []byte) (offset int) {
	if x.Id == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetId())
	return offset
}

func (x *SocialContent) fastWriteField2(buf []byte) (offset int) {
	if x.Title == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 2, x.GetTitle())
	return offset
}

func (x *SocialContent) fastWriteField3(buf []byte) (offset int) {
	if x.SourceKeyword == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 3, x.GetSourceKeyword())
	return offset
}

func (x *SocialContent) fastWriteField4(buf []byte) (offset int) {
	if x.Platform == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 4, x.GetPlatform())
	return offset
}

func (x *ListMyOrganizationsRequest) Size() (n int) {
	if x == nil {
		return n
	}
	return n
}

func (x *ListMyOrganizationsResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *ListMyOrganizationsResponse) sizeField1() (n int) {
	if x.Organizations == nil {
		return n
	}
	for i := range x.GetOrganizations() {
		n += fastpb.SizeMessage(1, x.GetOrganizations()[i])
	}
	return n
}

func (x *OrganizationMembership) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *OrganizationMembership) sizeField1() (n int) {
	if x.Id == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetId())
	return n
}

func (x *OrganizationMembership) sizeField2() (n int) {
	if len(x.Roles) == 0 {
		return n
	}
	for i := range x.GetRoles() {
		n += fastpb.SizeString(2, x.GetRoles()[i])
	}
	return n
}

func (x *SearchContentsRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *SearchContentsRequest) sizeField1() (n int) {
	if x.OrganizationId == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetOrganizationId())
	return n
}

func (x *SearchContentsRequest) sizeField2() (n int) {
	if x.Keyword == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetKeyword())
	return n
}

func (x *SearchContentsResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *SearchContentsResponse) sizeField1() (n int) {
	if x.Contents == nil {
		return n
	}
	for i := range x.GetContents() {
		n += fastpb.SizeMessage(1, x.GetContents()[i])
	}
	return n
}

func (x *SocialContent) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	n += x.sizeField3()
	n += x.sizeField4()
	return n
}

func (x *SocialContent) sizeField1() (n int) {
	if x.Id == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetId())
	return n
}

func (x *SocialContent) sizeField2() (n int) {
	if x.Title == "" {
		return n
	}
	n += fastpb.SizeString(2, x.GetTitle())
	return n
}

func (x *SocialContent) sizeField3() (n int) {
	if x.SourceKeyword == "" {
		return n
	}
	n += fastpb.SizeString(3, x.GetSourceKeyword())
	return n
}

func (x *SocialContent) sizeField4() (n int) {
	if x.Platform == "" {
		return n
	}
	n += fastpb.SizeString(4, x.GetPlatform())
	return n
}

var fieldIDToName_ListMyOrganizationsRequest = map[int32]string{}

var fieldIDToName_ListMyOrganizationsResponse = map[int32]string{
	1: "Organizations",
}

var fieldIDToName_OrganizationMembership = map[int32]string{
	1: "Id",
	2: "Roles",
}

var fieldIDToName_SearchContentsRequest = map[int32]string{
	1: "OrganizationId",
	2: "Keyword",
}

var fieldIDToName_SearchContentsResponse = map[int32]string{
	1: "Contents",
}

var fieldIDToName_SocialContent = map[int32]string{
	1: "Id",
	2: "Title",
	3: "SourceKeyword",
	4: "Platform",
}

var _ = annotations.File_google_api_annotations_proto
