// Code generated by hertz generator.

package crawl_service

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/protocol"
	crawl "media_agent/hertz_gen/model/xhs_service/crawl"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type Client interface {
	StartCrawlTask(context context.Context, req *crawl.StartCrawlTaskRequest, reqOpt ...config.RequestOption) (resp *crawl.StartCrawlTaskResponse, rawResponse *protocol.Response, err error)

	ListCrawlContents(context context.Context, req *crawl.ListCrawlContentsRequest, reqOpt ...config.RequestOption) (resp *crawl.ListCrawlContentsResponse, rawResponse *protocol.Response, err error)

	GetKeywords(context context.Context, req *crawl.GetKeywordsRequest, reqOpt ...config.RequestOption) (resp *crawl.GetKeywordsResponse, rawResponse *protocol.Response, err error)

	UpdateKeywords(context context.Context, req *crawl.UpdateKeywordsRequest, reqOpt ...config.RequestOption) (resp *crawl.UpdateKeywordsResponse, rawResponse *protocol.Response, err error)
}

type CrawlServiceClient struct {
	client *cli
}

func NewCrawlServiceClient(hostUrl string, ops ...Option) (Client, error) {
	opts := getOptions(append(ops, withHostUrl(hostUrl))...)
	cli, err := newClient(opts)
	if err != nil {
		return nil, err
	}
	return &CrawlServiceClient{
		client: cli,
	}, nil
}

func (s *CrawlServiceClient) StartCrawlTask(context context.Context, req *crawl.StartCrawlTaskRequest, reqOpt ...config.RequestOption) (resp *crawl.StartCrawlTaskResponse, rawResponse *protocol.Response, err error) {
	httpResp := &crawl.StartCrawlTaskResponse{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{
			"organization_id": req.GetOrganizationId(),
		}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("POST", "/v1/xhs/organizations/:organization_id/crawl/tasks")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *CrawlServiceClient) ListCrawlContents(context context.Context, req *crawl.ListCrawlContentsRequest, reqOpt ...config.RequestOption) (resp *crawl.ListCrawlContentsResponse, rawResponse *protocol.Response, err error) {
	httpResp := &crawl.ListCrawlContentsResponse{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{
			"organization_id": req.GetOrganizationId(),
		}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("GET", "/v1/xhs/organizations/:organization_id/crawl/contents")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *CrawlServiceClient) GetKeywords(context context.Context, req *crawl.GetKeywordsRequest, reqOpt ...config.RequestOption) (resp *crawl.GetKeywordsResponse, rawResponse *protocol.Response, err error) {
	httpResp := &crawl.GetKeywordsResponse{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{
			"organization_id": req.GetOrganizationId(),
		}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("GET", "/v1/xhs/organizations/:organization_id/crawl/keywords")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *CrawlServiceClient) UpdateKeywords(context context.Context, req *crawl.UpdateKeywordsRequest, reqOpt ...config.RequestOption) (resp *crawl.UpdateKeywordsResponse, rawResponse *protocol.Response, err error) {
	httpResp := &crawl.UpdateKeywordsResponse{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{
			"organization_id": req.GetOrganizationId(),
		}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("PUT", "/v1/xhs/organizations/:organization_id/crawl/keywords")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

var defaultClient, _ = NewCrawlServiceClient("")

func ConfigDefaultClient(ops ...Option) (err error) {
	defaultClient, err = NewCrawlServiceClient("", ops...)
	return
}

func StartCrawlTask(context context.Context, req *crawl.StartCrawlTaskRequest, reqOpt ...config.RequestOption) (resp *crawl.StartCrawlTaskResponse, rawResponse *protocol.Response, err error) {
	return defaultClient.StartCrawlTask(context, req, reqOpt...)
}

func ListCrawlContents(context context.Context, req *crawl.ListCrawlContentsRequest, reqOpt ...config.RequestOption) (resp *crawl.ListCrawlContentsResponse, rawResponse *protocol.Response, err error) {
	return defaultClient.ListCrawlContents(context, req, reqOpt...)
}

func GetKeywords(context context.Context, req *crawl.GetKeywordsRequest, reqOpt ...config.RequestOption) (resp *crawl.GetKeywordsResponse, rawResponse *protocol.Response, err error) {
	return defaultClient.GetKeywords(context, req, reqOpt...)
}

func UpdateKeywords(context context.Context, req *crawl.UpdateKeywordsRequest, reqOpt ...config.RequestOption) (resp *crawl.UpdateKeywordsResponse, rawResponse *protocol.Response, err error) {
	return defaultClient.UpdateKeywords(context, req, reqOpt...)
}
