// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	crawl "media_agent/xhs_service/biz/router/crawl"
	organization "media_agent/xhs_service/biz/router/organization"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	organization.Register(r)

	crawl.Register(r)
}
