apiVersion: v1
kind: Service
metadata:
  name: {{ include "xhs.fullname" . }}
  labels:
    {{- include "xhs.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}
      {{- with .Values.service.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
  selector:
    {{- include "xhs.selectorLabels" . | nindent 4 }}
