// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *HealthCheckRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_HealthCheckRequest[number], err)
}

func (x *HealthCheckRequest) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Service, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *HealthCheckResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_HealthCheckResponse[number], err)
}

func (x *HealthCheckResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v int32
	v, offset, err = fastpb.ReadInt32(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Status = HealthCheckResponse_ServingStatus(v)
	return offset, nil
}

func (x *HealthCheckRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *HealthCheckRequest) fastWriteField1(buf []byte) (offset int) {
	if x.Service == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetService())
	return offset
}

func (x *HealthCheckResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *HealthCheckResponse) fastWriteField1(buf []byte) (offset int) {
	if x.Status == 0 {
		return offset
	}
	offset += fastpb.WriteInt32(buf[offset:], 1, int32(x.GetStatus()))
	return offset
}

func (x *HealthCheckRequest) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *HealthCheckRequest) sizeField1() (n int) {
	if x.Service == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetService())
	return n
}

func (x *HealthCheckResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *HealthCheckResponse) sizeField1() (n int) {
	if x.Status == 0 {
		return n
	}
	n += fastpb.SizeInt32(1, int32(x.GetStatus()))
	return n
}

var fieldIDToName_HealthCheckRequest = map[int32]string{
	1: "Service",
}

var fieldIDToName_HealthCheckResponse = map[int32]string{
	1: "Status",
}
