// Code generated by Kitex v0.11.3. DO NOT EDIT.

package socialservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	social_service "media_agent/social_grpc/kitex_gen/social_service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListMyOrganizations(ctx context.Context, Req *social_service.ListMyOrganizationsRequest, callOptions ...callopt.Option) (r *social_service.ListMyOrganizationsResponse, err error)
	SearchContents(ctx context.Context, Req *social_service.SearchContentsRequest, callOptions ...callopt.Option) (r *social_service.SearchContentsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialServiceClient struct {
	*kClient
}

func (p *kSocialServiceClient) ListMyOrganizations(ctx context.Context, Req *social_service.ListMyOrganizationsRequest, callOptions ...callopt.Option) (r *social_service.ListMyOrganizationsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListMyOrganizations(ctx, Req)
}

func (p *kSocialServiceClient) SearchContents(ctx context.Context, Req *social_service.SearchContentsRequest, callOptions ...callopt.Option) (r *social_service.SearchContentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchContents(ctx, Req)
}
