// Code generated by Kitex v0.11.3. DO NOT EDIT.
package socialservice

import (
	server "github.com/cloudwego/kitex/server"
	social_service "media_agent/social_grpc/kitex_gen/social_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler social_service.SocialService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler social_service.SocialService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
