// Code generated by Kitex v0.11.3. DO NOT EDIT.

package socialservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	social_service "media_agent/social_grpc/kitex_gen/social_service"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListMyOrganizations": kitex.NewMethodInfo(
		listMyOrganizationsHandler,
		newListMyOrganizationsArgs,
		newListMyOrganizationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchContents": kitex.NewMethodInfo(
		searchContentsHandler,
		newSearchContentsArgs,
		newSearchContentsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	socialServiceServiceInfo                = NewServiceInfo()
	socialServiceServiceInfoForClient       = NewServiceInfoForClient()
	socialServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return socialServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return socialServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return socialServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SocialService"
	handlerType := (*social_service.SocialService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "social_service",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func listMyOrganizationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(social_service.ListMyOrganizationsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(social_service.SocialService).ListMyOrganizations(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListMyOrganizationsArgs:
		success, err := handler.(social_service.SocialService).ListMyOrganizations(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListMyOrganizationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListMyOrganizationsArgs() interface{} {
	return &ListMyOrganizationsArgs{}
}

func newListMyOrganizationsResult() interface{} {
	return &ListMyOrganizationsResult{}
}

type ListMyOrganizationsArgs struct {
	Req *social_service.ListMyOrganizationsRequest
}

func (p *ListMyOrganizationsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(social_service.ListMyOrganizationsRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListMyOrganizationsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListMyOrganizationsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListMyOrganizationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListMyOrganizationsArgs) Unmarshal(in []byte) error {
	msg := new(social_service.ListMyOrganizationsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListMyOrganizationsArgs_Req_DEFAULT *social_service.ListMyOrganizationsRequest

func (p *ListMyOrganizationsArgs) GetReq() *social_service.ListMyOrganizationsRequest {
	if !p.IsSetReq() {
		return ListMyOrganizationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListMyOrganizationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListMyOrganizationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListMyOrganizationsResult struct {
	Success *social_service.ListMyOrganizationsResponse
}

var ListMyOrganizationsResult_Success_DEFAULT *social_service.ListMyOrganizationsResponse

func (p *ListMyOrganizationsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(social_service.ListMyOrganizationsResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListMyOrganizationsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListMyOrganizationsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListMyOrganizationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListMyOrganizationsResult) Unmarshal(in []byte) error {
	msg := new(social_service.ListMyOrganizationsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListMyOrganizationsResult) GetSuccess() *social_service.ListMyOrganizationsResponse {
	if !p.IsSetSuccess() {
		return ListMyOrganizationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListMyOrganizationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*social_service.ListMyOrganizationsResponse)
}

func (p *ListMyOrganizationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListMyOrganizationsResult) GetResult() interface{} {
	return p.Success
}

func searchContentsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(social_service.SearchContentsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(social_service.SocialService).SearchContents(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchContentsArgs:
		success, err := handler.(social_service.SocialService).SearchContents(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchContentsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchContentsArgs() interface{} {
	return &SearchContentsArgs{}
}

func newSearchContentsResult() interface{} {
	return &SearchContentsResult{}
}

type SearchContentsArgs struct {
	Req *social_service.SearchContentsRequest
}

func (p *SearchContentsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(social_service.SearchContentsRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SearchContentsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SearchContentsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SearchContentsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchContentsArgs) Unmarshal(in []byte) error {
	msg := new(social_service.SearchContentsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchContentsArgs_Req_DEFAULT *social_service.SearchContentsRequest

func (p *SearchContentsArgs) GetReq() *social_service.SearchContentsRequest {
	if !p.IsSetReq() {
		return SearchContentsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchContentsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchContentsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchContentsResult struct {
	Success *social_service.SearchContentsResponse
}

var SearchContentsResult_Success_DEFAULT *social_service.SearchContentsResponse

func (p *SearchContentsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(social_service.SearchContentsResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SearchContentsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SearchContentsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SearchContentsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchContentsResult) Unmarshal(in []byte) error {
	msg := new(social_service.SearchContentsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchContentsResult) GetSuccess() *social_service.SearchContentsResponse {
	if !p.IsSetSuccess() {
		return SearchContentsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchContentsResult) SetSuccess(x interface{}) {
	p.Success = x.(*social_service.SearchContentsResponse)
}

func (p *SearchContentsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchContentsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListMyOrganizations(ctx context.Context, Req *social_service.ListMyOrganizationsRequest) (r *social_service.ListMyOrganizationsResponse, err error) {
	var _args ListMyOrganizationsArgs
	_args.Req = Req
	var _result ListMyOrganizationsResult
	if err = p.c.Call(ctx, "ListMyOrganizations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchContents(ctx context.Context, Req *social_service.SearchContentsRequest) (r *social_service.SearchContentsResponse, err error) {
	var _args SearchContentsArgs
	_args.Req = Req
	var _result SearchContentsResult
	if err = p.c.Call(ctx, "SearchContents", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
