// Code generated by hertz generator.

package crawl

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _organizationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _organization_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _crawlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listcrawlcontentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getkeywordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatekeywordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _startcrawltaskMw() []app.HandlerFunc {
	// your code...
	return nil
}
