// Code generated by Kitex v0.11.3. DO NOT EDIT.

package organizationservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	organization "media_agent/xhs_grpc/kitex_gen/xhs_service/organization"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListMyOrganizations": kitex.NewMethodInfo(
		listMyOrganizationsHandler,
		newListMyOrganizationsArgs,
		newListMyOrganizationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	organizationServiceServiceInfo                = NewServiceInfo()
	organizationServiceServiceInfoForClient       = NewServiceInfoForClient()
	organizationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return organizationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return organizationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return organizationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrganizationService"
	handlerType := (*organization.OrganizationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "xhs_service.organization",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func listMyOrganizationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(organization.ListMyOrganizationsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(organization.OrganizationService).ListMyOrganizations(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ListMyOrganizationsArgs:
		success, err := handler.(organization.OrganizationService).ListMyOrganizations(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ListMyOrganizationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newListMyOrganizationsArgs() interface{} {
	return &ListMyOrganizationsArgs{}
}

func newListMyOrganizationsResult() interface{} {
	return &ListMyOrganizationsResult{}
}

type ListMyOrganizationsArgs struct {
	Req *organization.ListMyOrganizationsRequest
}

func (p *ListMyOrganizationsArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(organization.ListMyOrganizationsRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ListMyOrganizationsArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ListMyOrganizationsArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ListMyOrganizationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ListMyOrganizationsArgs) Unmarshal(in []byte) error {
	msg := new(organization.ListMyOrganizationsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ListMyOrganizationsArgs_Req_DEFAULT *organization.ListMyOrganizationsRequest

func (p *ListMyOrganizationsArgs) GetReq() *organization.ListMyOrganizationsRequest {
	if !p.IsSetReq() {
		return ListMyOrganizationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ListMyOrganizationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ListMyOrganizationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ListMyOrganizationsResult struct {
	Success *organization.ListMyOrganizationsResponse
}

var ListMyOrganizationsResult_Success_DEFAULT *organization.ListMyOrganizationsResponse

func (p *ListMyOrganizationsResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(organization.ListMyOrganizationsResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ListMyOrganizationsResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ListMyOrganizationsResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ListMyOrganizationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ListMyOrganizationsResult) Unmarshal(in []byte) error {
	msg := new(organization.ListMyOrganizationsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ListMyOrganizationsResult) GetSuccess() *organization.ListMyOrganizationsResponse {
	if !p.IsSetSuccess() {
		return ListMyOrganizationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ListMyOrganizationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*organization.ListMyOrganizationsResponse)
}

func (p *ListMyOrganizationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ListMyOrganizationsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListMyOrganizations(ctx context.Context, Req *organization.ListMyOrganizationsRequest) (r *organization.ListMyOrganizationsResponse, err error) {
	var _args ListMyOrganizationsArgs
	_args.Req = Req
	var _result ListMyOrganizationsResult
	if err = p.c.Call(ctx, "ListMyOrganizations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
