// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package organization

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
	annotations "google.golang.org/genproto/googleapis/api/annotations"
	api "media_agent/xhs_grpc/kitex_gen/api"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *ListMyOrganizationsRequest) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
}

func (x *ListMyOrganizationsResponse) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_ListMyOrganizationsResponse[number], err)
}

func (x *ListMyOrganizationsResponse) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	var v OrganizationMembership
	offset, err = fastpb.ReadMessage(buf, _type, &v)
	if err != nil {
		return offset, err
	}
	x.Organizations = append(x.Organizations, &v)
	return offset, nil
}

func (x *OrganizationMembership) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_OrganizationMembership[number], err)
}

func (x *OrganizationMembership) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Id, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *OrganizationMembership) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	var v string
	v, offset, err = fastpb.ReadString(buf, _type)
	if err != nil {
		return offset, err
	}
	x.Roles = append(x.Roles, v)
	return offset, err
}

func (x *ListMyOrganizationsRequest) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	return offset
}

func (x *ListMyOrganizationsResponse) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *ListMyOrganizationsResponse) fastWriteField1(buf []byte) (offset int) {
	if x.Organizations == nil {
		return offset
	}
	for i := range x.GetOrganizations() {
		offset += fastpb.WriteMessage(buf[offset:], 1, x.GetOrganizations()[i])
	}
	return offset
}

func (x *OrganizationMembership) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *OrganizationMembership) fastWriteField1(buf []byte) (offset int) {
	if x.Id == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetId())
	return offset
}

func (x *OrganizationMembership) fastWriteField2(buf []byte) (offset int) {
	if len(x.Roles) == 0 {
		return offset
	}
	for i := range x.GetRoles() {
		offset += fastpb.WriteString(buf[offset:], 2, x.GetRoles()[i])
	}
	return offset
}

func (x *ListMyOrganizationsRequest) Size() (n int) {
	if x == nil {
		return n
	}
	return n
}

func (x *ListMyOrganizationsResponse) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *ListMyOrganizationsResponse) sizeField1() (n int) {
	if x.Organizations == nil {
		return n
	}
	for i := range x.GetOrganizations() {
		n += fastpb.SizeMessage(1, x.GetOrganizations()[i])
	}
	return n
}

func (x *OrganizationMembership) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *OrganizationMembership) sizeField1() (n int) {
	if x.Id == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetId())
	return n
}

func (x *OrganizationMembership) sizeField2() (n int) {
	if len(x.Roles) == 0 {
		return n
	}
	for i := range x.GetRoles() {
		n += fastpb.SizeString(2, x.GetRoles()[i])
	}
	return n
}

var fieldIDToName_ListMyOrganizationsRequest = map[int32]string{}

var fieldIDToName_ListMyOrganizationsResponse = map[int32]string{
	1: "Organizations",
}

var fieldIDToName_OrganizationMembership = map[int32]string{
	1: "Id",
	2: "Roles",
}

var _ = api.File_api_proto
var _ = annotations.File_google_api_annotations_proto
