// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.0
// source: xhs_service/organization.proto

package organization

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "media_agent/xhs_grpc/kitex_gen/api"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListMyOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrganizationsRequest) Reset() {
	*x = ListMyOrganizationsRequest{}
	mi := &file_xhs_service_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrganizationsRequest) ProtoMessage() {}

func (x *ListMyOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListMyOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_xhs_service_organization_proto_rawDescGZIP(), []int{0}
}

type ListMyOrganizationsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Organizations []*OrganizationMembership `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrganizationsResponse) Reset() {
	*x = ListMyOrganizationsResponse{}
	mi := &file_xhs_service_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrganizationsResponse) ProtoMessage() {}

func (x *ListMyOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListMyOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_xhs_service_organization_proto_rawDescGZIP(), []int{1}
}

func (x *ListMyOrganizationsResponse) GetOrganizations() []*OrganizationMembership {
	if x != nil {
		return x.Organizations
	}
	return nil
}

type OrganizationMembership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMembership) Reset() {
	*x = OrganizationMembership{}
	mi := &file_xhs_service_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMembership) ProtoMessage() {}

func (x *OrganizationMembership) ProtoReflect() protoreflect.Message {
	mi := &file_xhs_service_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMembership.ProtoReflect.Descriptor instead.
func (*OrganizationMembership) Descriptor() ([]byte, []int) {
	return file_xhs_service_organization_proto_rawDescGZIP(), []int{2}
}

func (x *OrganizationMembership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationMembership) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_xhs_service_organization_proto protoreflect.FileDescriptor

const file_xhs_service_organization_proto_rawDesc = "" +
	"\n" +
	"\x1exhs_service/organization.proto\x12\x18xhs_service.organization\x1a\tapi.proto\x1a\x1cgoogle/api/annotations.proto\"\x1c\n" +
	"\x1aListMyOrganizationsRequest\"u\n" +
	"\x1bListMyOrganizationsResponse\x12V\n" +
	"\rorganizations\x18\x01 \x03(\v20.xhs_service.organization.OrganizationMembershipR\rorganizations\">\n" +
	"\x16OrganizationMembership\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles2\xd8\x01\n" +
	"\x13OrganizationService\x12\xc0\x01\n" +
	"\x13ListMyOrganizations\x124.xhs_service.organization.ListMyOrganizationsRequest\x1a5.xhs_service.organization.ListMyOrganizationsResponse\"<\xca\xc1\x18\x18/v1/xhs/me/organizations\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/xhs/me/organizationsB9Z7media_agent/xhs_grpc/kitex_gen/xhs_service/organizationb\x06proto3"

var (
	file_xhs_service_organization_proto_rawDescOnce sync.Once
	file_xhs_service_organization_proto_rawDescData []byte
)

func file_xhs_service_organization_proto_rawDescGZIP() []byte {
	file_xhs_service_organization_proto_rawDescOnce.Do(func() {
		file_xhs_service_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xhs_service_organization_proto_rawDesc), len(file_xhs_service_organization_proto_rawDesc)))
	})
	return file_xhs_service_organization_proto_rawDescData
}

var file_xhs_service_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_xhs_service_organization_proto_goTypes = []any{
	(*ListMyOrganizationsRequest)(nil),  // 0: xhs_service.organization.ListMyOrganizationsRequest
	(*ListMyOrganizationsResponse)(nil), // 1: xhs_service.organization.ListMyOrganizationsResponse
	(*OrganizationMembership)(nil),      // 2: xhs_service.organization.OrganizationMembership
}
var file_xhs_service_organization_proto_depIdxs = []int32{
	2, // 0: xhs_service.organization.ListMyOrganizationsResponse.organizations:type_name -> xhs_service.organization.OrganizationMembership
	0, // 1: xhs_service.organization.OrganizationService.ListMyOrganizations:input_type -> xhs_service.organization.ListMyOrganizationsRequest
	1, // 2: xhs_service.organization.OrganizationService.ListMyOrganizations:output_type -> xhs_service.organization.ListMyOrganizationsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xhs_service_organization_proto_init() }
func file_xhs_service_organization_proto_init() {
	if File_xhs_service_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xhs_service_organization_proto_rawDesc), len(file_xhs_service_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xhs_service_organization_proto_goTypes,
		DependencyIndexes: file_xhs_service_organization_proto_depIdxs,
		MessageInfos:      file_xhs_service_organization_proto_msgTypes,
	}.Build()
	File_xhs_service_organization_proto = out.File
	file_xhs_service_organization_proto_goTypes = nil
	file_xhs_service_organization_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.11.3. DO NOT EDIT.

type OrganizationService interface {
	ListMyOrganizations(ctx context.Context, req *ListMyOrganizationsRequest) (res *ListMyOrganizationsResponse, err error)
}
