// Code generated by hertz generator.

package organization_service

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/protocol"
	organization "media_agent/hertz_gen/model/xhs_service/organization"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type Client interface {
	ListMyOrganizations(context context.Context, req *organization.ListMyOrganizationsRequest, reqOpt ...config.RequestOption) (resp *organization.ListMyOrganizationsResponse, rawResponse *protocol.Response, err error)
}

type OrganizationServiceClient struct {
	client *cli
}

func NewOrganizationServiceClient(hostUrl string, ops ...Option) (Client, error) {
	opts := getOptions(append(ops, withHostUrl(hostUrl))...)
	cli, err := newClient(opts)
	if err != nil {
		return nil, err
	}
	return &OrganizationServiceClient{
		client: cli,
	}, nil
}

func (s *OrganizationServiceClient) ListMyOrganizations(context context.Context, req *organization.ListMyOrganizationsRequest, reqOpt ...config.RequestOption) (resp *organization.ListMyOrganizationsResponse, rawResponse *protocol.Response, err error) {
	httpResp := &organization.ListMyOrganizationsResponse{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("GET", "/v1/xhs/me/organizations")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

var defaultClient, _ = NewOrganizationServiceClient("")

func ConfigDefaultClient(ops ...Option) (err error) {
	defaultClient, err = NewOrganizationServiceClient("", ops...)
	return
}

func ListMyOrganizations(context context.Context, req *organization.ListMyOrganizationsRequest, reqOpt ...config.RequestOption) (resp *organization.ListMyOrganizationsResponse, rawResponse *protocol.Response, err error) {
	return defaultClient.ListMyOrganizations(context, req, reqOpt...)
}
