// Code generated by hertz generator.

package health_service

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/protocol"
	health "media_agent/hertz_gen/model/xhs_service/health"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type Client interface {
	Health(context context.Context, req *health.HealthRequest, reqOpt ...config.RequestOption) (resp *health.HealthResponse, rawResponse *protocol.Response, err error)
}

type HealthServiceClient struct {
	client *cli
}

func NewHealthServiceClient(hostUrl string, ops ...Option) (Client, error) {
	opts := getOptions(append(ops, withHostUrl(hostUrl))...)
	cli, err := newClient(opts)
	if err != nil {
		return nil, err
	}
	return &HealthServiceClient{
		client: cli,
	}, nil
}

func (s *HealthServiceClient) Health(context context.Context, req *health.HealthRequest, reqOpt ...config.RequestOption) (resp *health.HealthResponse, rawResponse *protocol.Response, err error) {
	httpResp := &health.HealthResponse{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		addHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("GET", "/health")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

var defaultClient, _ = NewHealthServiceClient("")

func ConfigDefaultClient(ops ...Option) (err error) {
	defaultClient, err = NewHealthServiceClient("", ops...)
	return
}

func Health(context context.Context, req *health.HealthRequest, reqOpt ...config.RequestOption) (resp *health.HealthResponse, rawResponse *protocol.Response, err error) {
	return defaultClient.Health(context, req, reqOpt...)
}
