apiVersion: v1
kind: Namespace
metadata:
  name: ddd-learn
---
apiVersion: v1
kind: Secret
metadata:
  name: ddd-learn-postgres-credentials
  namespace: ddd-learn
type: kubernetes.io/basic-auth
stringData:
  username: ory
  password: ory
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ddd-learn-postgres
  namespace: ddd-learn
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 5Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: ory
      owner: ory
      secret:
        name: ddd-learn-postgres-credentials
      postInitSQL:
        - CREATE ROLE keto LOGIN PASSWORD 'keto';
        - CREATE DATABASE keto OWNER keto;
