// Code generated by hertz generator.

package organization

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	organization "media_agent/hertz_gen/model/xhs_service/organization"
	serverjwt "media_agent/hertz_infra/serverhertz/jwt"
	service "media_agent/xhs_service/biz/service/organization"
)

// ListMyOrganizations .
// @router /v1/xhs/me/organizations [GET]
func ListMyOrganizations(ctx context.Context, c *app.RequestContext) {
	var err error
	var req organization.ListMyOrganizationsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if organizationService == nil {
		c.AbortWithStatusJSON(consts.StatusInternalServerError, map[string]any{"error": "organization service is not configured"})
		return
	}
	principal, ok := serverjwt.PrincipalFromContext(ctx)
	if !ok {
		writeServiceError(c, service.ErrUnauthenticated)
		return
	}
	organizations, err := organizationService.ListMine(ctx, principal.Subject)
	if err != nil {
		writeServiceError(c, err)
		return
	}

	resp := new(organization.ListMyOrganizationsResponse)
	for _, item := range organizations {
		resp.Organizations = append(resp.Organizations, &organization.OrganizationMembership{Id: item.ID, Roles: item.Roles})
	}
	c.JSON(consts.StatusOK, resp)
}

func writeServiceError(c *app.RequestContext, err error) {
	status := consts.StatusInternalServerError
	switch {
	case errors.Is(err, service.ErrUnauthenticated):
		status = consts.StatusUnauthorized
	case errors.Is(err, service.ErrDependencyUnavailable):
		status = consts.StatusServiceUnavailable
	}
	c.AbortWithStatusJSON(status, map[string]any{"error": err.Error()})
}
